package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"errors"
	"github.com/99designs/gqlgen/graphql"

	"github.com/customeros/leads/api/graphql/graphql_model"
	"github.com/customeros/leads/api/graphql/mappers"
	"github.com/customeros/leads/internal/models"
	"github.com/customeros/leads/internal/telemetry"
	"github.com/customeros/leads/internal/utils"
)

// CreateWebtracker is the resolver for the createWebtracker field.
func (r *mutationResolver) CreateWebtracker(ctx context.Context, tracker graphql_model.WebtrackerSaveInput) (*graphql_model.Webtracker, error) {
	span, ctx := telemetry.StartGraphQLSpan(ctx, "mutationResolver.CreateWebtracker", graphql.GetOperationContext(ctx))
	defer span.Finish()
	span.LogObjectAsJson("request.input", tracker)

	cnameHost := ""
	if tracker.CnameHost != nil {
		cnameHost = *tracker.CnameHost
		if !utils.IsLowerAlphanumeric(cnameHost) {
			err := errors.New("Invalid CNAME Host")
			span.TraceError(err)
			return nil, err
		}
	}

	newTracker := &models.WebTracker{
		ID:        utils.GenerateNanoIDWithPrefix("trkr", 16),
		Domain:    tracker.Domain,
		CNAMEHost: cnameHost,
	}

	createdWebtracker, err := r.services.WebtrackerService.CreateWebtracker(ctx, newTracker)
	if err != nil {
		span.TraceError(err)
		return nil, err
	}

	return mappers.ToWebtrackerGraphQL(createdWebtracker), nil
}

// UpdateWebtracker is the resolver for the updateWebtracker field.
func (r *mutationResolver) UpdateWebtracker(ctx context.Context, tracker graphql_model.WebtrackerSaveInput) (*graphql_model.Webtracker, error) {
	span, ctx := telemetry.StartGraphQLSpan(ctx, "mutationResolver.UpdateWebtracker", graphql.GetOperationContext(ctx))
	defer span.Finish()

	if tracker.ID == nil || *tracker.ID == "" {
		err := errors.New("ID is required to update webtracker")
		span.TraceError(err)
		return nil, err
	}

	cnameHost := ""
	if tracker.CnameHost != nil {
		cnameHost = *tracker.CnameHost
		if !utils.IsLowerAlphanumeric(cnameHost) {
			err := errors.New("Invalid CNAME Host")
			span.TraceError(err)
			return nil, err
		}
	}

	updatedTracker, err := r.services.WebtrackerService.UpdateCNAMEHost(ctx, *tracker.ID, cnameHost)
	if err != nil {
		span.TraceError(err)
		return nil, err
	}

	return mappers.ToWebtrackerGraphQL(updatedTracker), nil
}

// VerifyWebtrackerCname is the resolver for the verifyWebtrackerCname field.
func (r *mutationResolver) VerifyWebtrackerCname(ctx context.Context, id string) (bool, error) {
	span, ctx := telemetry.StartGraphQLSpan(ctx, "mutationResolver.VerifyWebtrackerCname", graphql.GetOperationContext(ctx))
	defer span.Finish()

	if id == "" {
		err := errors.New("ID cannot be empty")
		span.TraceError(err)
		return false, err
	}

	return r.services.WebtrackerService.IsCNAMEConfigured(ctx, id)
}

// ArchiveWebtracker is the resolver for the archiveWebtracker field.
func (r *mutationResolver) ArchiveWebtracker(ctx context.Context, id string) (bool, error) {
	span, ctx := telemetry.StartGraphQLSpan(ctx, "mutationResolver.VerifyWebtrackerCname", graphql.GetOperationContext(ctx))
	defer span.Finish()

	if id == "" {
		err := errors.New("ID cannot be empty")
		span.TraceError(err)
		return false, err
	}

	err := r.services.WebtrackerService.ArchiveWebtracker(ctx, id)
	if err != nil {
		span.TraceError(err)
		return false, err
	}
	return true, nil
}

// Webtracker is the resolver for the webtracker field.
func (r *queryResolver) Webtracker(ctx context.Context, id string) (*graphql_model.Webtracker, error) {
	span, ctx := telemetry.StartGraphQLSpan(ctx, "queryResolver.Webtracker", graphql.GetOperationContext(ctx))
	defer span.Finish()

	if id == "" {
		err := errors.New("ID cannot be empty")
		span.TraceError(err)
		return nil, err
	}

	tracker, err := r.services.WebtrackerService.GetWebtracker(ctx, id)
	if err != nil {
		span.TraceError(err)
		return nil, err
	}

	return mappers.ToWebtrackerGraphQL(tracker), nil
}

// Webtrackers is the resolver for the webtrackers field.
func (r *queryResolver) Webtrackers(ctx context.Context) ([]*graphql_model.Webtracker, error) {
	span, ctx := telemetry.StartGraphQLSpan(ctx, "queryResolver.Webtrackers", graphql.GetOperationContext(ctx))
	defer span.Finish()

	webtrackers, err := r.services.WebtrackerService.GetActiveWebtrackers(ctx)
	if err != nil {
		span.TraceError(err)
		return nil, err
	}

	return mappers.ToWebtrackerGraphQLSlice(webtrackers), nil
}
